### ISSUE TITLE
Site should have atom feeds

### ISSUE THREAD

**Issue by 153** [Flameborn/Kiramoji#1]
1. latest threads
2. latest comments within thread
3. global latest comments

These 3 factors together provide a powerful base for many alternate clients and addons while requiring very little work of an administrator.

**Comment by Flameborn** [comment]
Feeds are not meant to provide a complete rundown of a Kiramoji site in this case, hence the existing RSS implementation is very minimalistic by design. It is designed more for keeping up with threads, rather than keeping up with content, as it's the case with other media, such as blogs or podcasts.

I thought about supporting RSS only, but in the end, having better compatibility with readers is always a good idea. So, I've just added Atom support. ☺️

It works similarly to the already available RSS feed, as in, it lists the recently updated threads along with their post count.

Adding more than this would require a redesign, as I wouldn't like to leave RSS behind, but I believe this largely achieves what you're looking for, i.e. you have updated and new threads, as well as the number of posts per thread in a feed.
